# vim: ai:ts=2:sw=2:et
version: "3.4"
networks: {}
volumes: {}

x-custom:
  version: 1.0.0
  type: magento-2-module
  environment: &env-vars
    # Environment settings
    - "HOME=${CHOME}"
    - COMPOSER_MEMORY_LIMIT
    - XDEBUG_CONFIG
    - SSH_AUTH_SOCK

services:
  console:
    image: "eu.gcr.io/mct-deployments/magento-2-console:${PHP_VERSION}"
    user: "${UID}:${GID}"
    network_mode: bridge
    environment: *env-vars
    working_dir: "${PWD}"
    volumes:
      - "${HOME}:${CHOME}"
      - "${PWD}:${PWD}"
      - "${GCLOUD_LOCAL}:/config/mygcloud"
      - "${GIT_CONFIG_LOCAL}:/etc/gitconfig:ro"
      - "${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}"
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
