version: "3.4"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web-extra.address=:3200"
      - "--entrypoints.mysql.address=:3306"
      - "--entrypoints.kibana.address=:5601"
      - "--entrypoints.mailcatch.address=:8025"
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
      - "3200:3200"
      - "3306:3306"
      - "5601:5601"
      - "8025:8025"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  default:
    external:
      name: gateway
