# vim: ai:ts=2:sw=2:et
version: "3.4"
networks:
  backend: {}
  default:
    external:
      name: gateway
volumes:
  db-data:
  es-data:

x-custom:
  type: alumio
  version: 1.1.0

services:
  console:
    image: eu.gcr.io/aequalis-io/magement-console
    user: "${CUID}:${CGID}"
    links:
      - db
      - elasticsearch
      - mailcatch
    networks:
      - backend
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - DATABASE_URL
      - "HOME=${CHOME}"
      - MAGEMENT_ENV
      - MAGEMENT_SECRET
      - MYSQL_ROOT_PASSWORD
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_INSTANCE_URL=http://elasticsearch:9200
      - ELASTICSEARCH_INDEX=filebeat-*
      - SSH_AUTH_SOCK
      - XDEBUG_CONFIG
    working_dir: "${PWD}"
    volumes:
      - "${HOME}:${CHOME}"
      - "${PWD}:${PWD}"
      - "${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}"
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro

  dashboard:
    image: eu.gcr.io/aequalis-io/magement-dashboard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard_${PROJECT_NAME}.rule=Host(`dashboard.${DNS_NAME}`)"
      - "traefik.http.routers.dashboard_${PROJECT_NAME}.entrypoints=web"
      - "traefik.http.services.dashboard_${PROJECT_NAME}.loadbalancer.server.port=${DASHBOARD_PORT}"
      - "traefik.docker.network=gateway"
    networks:
      - backend
      - default

  db:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - backend
    labels:
      - "dev_domain=db.${PROJECT_NAME}.local"
    volumes:
      - db-data:/var/lib/mysql:rw

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    networks:
      - backend
    environment:
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data:rw

  filebeat:
    image: eu.gcr.io/aequalis-io/magement-filebeat
    networks:
      - backend
    command: filebeat -e -strict.perms=false
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - KIBANA_HOST=kibana
    links:
      - db
      - elasticsearch
      - web
      - worker
    volumes:
      - ./var/log:/usr/share/filebeat/data/app-logs:ro

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    links:
      - elasticsearch
    networks:
      - backend
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana_${PROJECT_NAME}.rule=Host(`kibana.${DNS_NAME}`)"
      - "traefik.http.routers.kibana_${PROJECT_NAME}.entrypoints=kibana"
      - "traefik.http.services.kibana_${PROJECT_NAME}.loadbalancer.server.port=${KIBANA_PORT}"
      - "traefik.docker.network=gateway"
    environment:
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  mailcatch:
    image: mailhog/mailhog
    networks:
      - backend
      - default

  web:
    image: eu.gcr.io/aequalis-io/magement-nginx
    links:
      - worker
    networks:
      - backend
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_${PROJECT_NAME}.rule=Host(`${DNS_NAME}`)"
      - "traefik.http.routers.web_{PROJECT_NAME}.entrypoints=web-extra"
      - "traefik.http.services.web_${PROJECT_NAME}.loadbalancer.server.port=${MAGEMENT_PORT}"
      - "traefik.docker.network=gateway"
    environment:
      - PHP_FPM_HOST=worker:9000
    working_dir: "${PWD}"
    volumes:
      - "${PWD}/web:${PWD}/web:ro"

  worker:
    image: eu.gcr.io/aequalis-io/magement-php-fpm
    user: "${CUID}:${CGID}"
    links:
      - db
      - elasticsearch
      - mailcatch
    networks:
      - backend
    environment:
      - DATABASE_URL
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - MAGEMENT_ENV
      - MAGEMENT_SECRET
      - PHP_EXTRA_CONFIGURE_ARGS
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_INSTANCE_URL=http://elasticsearch:9200
      - ELASTICSEARCH_INDEX=filebeat-*
      - XDEBUG_CONFIG
    working_dir: "${PWD}"
    volumes:
      - "${PWD}:${PWD}:rw"
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
